services:
  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      
  nginx:
    image: 211125691345.dkr.ecr.eu-west-2.amazonaws.com/covar_nginx:latest
    ports:
      - '80:80'
      - '443:443'      
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  api:
    image: 211125691345.dkr.ecr.eu-west-2.amazonaws.com/covar_api:latest
    environment:
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - JSON_SECRET=${JSON_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    depends_on:
      - postgres

  client:
    image: 211125691345.dkr.ecr.eu-west-2.amazonaws.com/covar_client:latest
    environment:
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
      - NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
      - NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
      - NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
      - NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}
      - NEXT_PUBLIC_MEASUREMENT_ID=${NEXT_PUBLIC_MEASUREMENT_ID}

volumes:
  postgres_data:
    driver: local