name: Build Codebase
on:
  push:
    branches: [ main, develop ]

  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  run_tests:
    name: Build Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.repository }}"
        uses: actions/checkout@v4

      - name: Set up Node v21
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Create .env file
        run: |
          echo PG_USER=${{ secrets.PG_USER }} >> .env
          echo PG_HOST=${{ secrets.PG_HOST }} >> .env
          echo PG_DATABASE=${{ secrets.PG_DATABASE }} >> .env
          echo PG_PASSWORD=${{ secrets.PG_PASSWORD }} >> .env
          echo PG_PORT=${{ secrets.PG_PORT }} >> .env
          echo JSON_SECRET=${{ secrets.JSON_SECRET }} >> .env
          echo REFRESH_SECRET=${{ secrets.REFRESH_SECRET }} >> .env
          echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env
          echo REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }} >> .env
          echo REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }} >> .env
          echo REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }} >> .env
          echo REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} >> .env
          echo REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }} >> .env
          echo REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }} >> .env

      - name: Install dependencies
        run:  |
          cd CoVAR-app && npm ci

      - name: Build Codebase
        run:  |
          cd CoVAR-app && npm run build