name: Lint Codebase
on:
  push:
    branches: [ main, develop ]

  pull_request:
    branches: [ main, develop ]
    
permissions:
  contents: read

jobs:
  lint_frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout "${{ github.repository }}"
        uses: actions/checkout@v3
      - name: Set up Node v22
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'

      - name: Install dependencies
        run:  |
          cd CoVAR-app && npm ci

      - name: Lint Codebase
        run:  |
          cd CoVAR-app && npm run lint
  
  lint_backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout "${{ github.repository }}"
        uses: actions/checkout@v3
      - name: Set up Node v22
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'

      - name: Install dependencies
        run:  |
          cd server && npm ci

      - name: Lint Codebase
        run:  |
          cd server && npm run lint