
name: Test Codebase
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  start:
    name: Initial Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Starting Job
        run: |
          echo "Beginning to test ${{ github.repository }}"

  run_tests:
    name: Test Codebase
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.repository }}"
        uses: actions/checkout@v4

      - name: Set up Node v21
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install dependencies
        run:  |
          cd covar-app && npm ci

      - name: Test Codebase
        run:  |
          cd covar-app && npm run test


      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-comment: true
          coverage-summary-path: ./covar-app/coverage/coverage-summary.json

      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

      - name: Create the badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 1793e26442bf0058d6c248da850c47f8
          filename: jest-coverage-comment__main.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}%
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: typescript

  end:
    name: The end
    runs-on: ubuntu-latest
    needs: [start, run_tests]
    steps:
      - name: Ending
        id: init
        run: |
          echo "${{ github.repository }} has passed all tests"